### ISSUE TITLE
Problem aSYNcrone

### ISSUE THREAD

**Issue by zergi-hub** [fatihsnsy/aSYNcrone#1]
GCC  problemThread : https://i.vgy.me/F5fAgZ.png

**Comment by fatihsnsy** [comment]
Please add the command into terminal:
-std=c99

**Comment by zergi-hub** [comment]
https://i.vgy.me/DpXVgT.png script not work

**Comment by fatihsnsy** [comment]
Yes, I will fix this. Thanks...
